// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahxopgndarkkyufdwkml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeG9wZ25kYXJra3l1ZmR3a21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDY5NTgsImV4cCI6MjA2NzQ4Mjk1OH0.j-N3SXpr6-yYNP87LR1yUvH75RoVPEuojCHnBJddmos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});